--CREATE TABLE IF NOT EXISTS enrollee (id BIGINT(20)  NOT NULL AUTO_INCREMENT, name VARCHAR(150) NOT NULL, activationStatus boolean NOT NULL, birthDate VARCHAR(20) NOT NULL, phoneNumber INT, PRIMARY KEY(id));
--CREATE TABLE IF NOT EXISTS dependants(id BIGINT(20)  NOT NULL AUTO_INCREMENT, enrollmentId BIGINT(20) NOT NULL, name VARCHAR(150) NOT NULL, birthDate VARCHAR(20) NOT NULL, PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS DAILY_TRANSACTION (id BIGINT(20)  NOT NULL AUTO_INCREMENT, userId VARCHAR(30) NOT NULL, amount DOUBLE NOT NULL, txnDate DATE  DEFAULT CURRENT_DATE,PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS MONTHLY_TRANSACTION (timeslot INT  NOT NULL , userId VARCHAR(30) NOT NULL, amount DOUBLE NOT NULL, PRIMARY KEY(timeslot,userId));

